### PR TITLE
Events

### PR DESCRIPTION
**Pull request by MyDigitalLife**
As stated in #10 there where a few events missing. This pull requests adds those events and also adds the completed events.

### CODE REVIEW

**Comment by MyDigitalLife** [comment]
@brexis Any chance your will be able to merge this any time soon?

**Comment by kmark** [comment]
In the meantime I created a rollup of your PRs and a few other changes at https://github.com/VersoBit/laravel-workflow/tree/rollup

To use add this to your composer.json:

```json
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/VersoBit/laravel-workflow"
    }
  ]
```

and then `composer require brexis/laravel-workflow:dev-rollup`

**Comment by lguima** [comment]
@kmark, it didn't work for me:

```
[Composer\Downloader\TransportException]                                                                                                    
  The "https://api.github.com/repos/VersoBit/laravel-workflow" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error  
   messages:                                                                                                                                  
  error:1408F10B:SSL routines:ssl3_get_record:wrong version number                                                                            
  Failed to enable crypto                                                                                                                     
  failed to open stream: operation failed
```

**Comment by kmark** [comment]
@lguima, that seems to be an error with GitHub or Composer

**Comment by lguima** [comment]
@Ben52 did you mean @MyDigitalLife or @kmark?

**Pull request merged**
