### PR TITLE
[wip] Add support for Laravel 7.0

### PR DESCRIPTION
**Pull request by riddla**
**Done**:
* Installed in conjunction with Laravel `7.0.8`
* Dump Workflows already successfully tested

**Todo**:
* Test different workflow scenarios

### CODE REVIEW

**Comment by devascolades** [comment]
Hello,
Thanks for your work.
I show a problem when using multiple_state.
I need to change arguments config file like this ;

 'marking_store' => [
            'type' => 'multiple_state',
                   'arguments' => [
                       'singleState' => false,
                       'property' =>'currentPlace',]

The function getCurrentPlace() and setCurrentPlace()  are unknown.

Fabien

**Comment by riddla** [comment]
@fabien44300, did this work before with the Laravel 6 version?
If not, I'm probably not able to help, because I'm not the original author of this package.

I think you got an answer over at https://github.com/zerodahero/laravel-workflow/issues/14#issuecomment-597707419 regarding your question?

**Comment by 4n70w4** [comment]
any news?

**Comment by riddla** [comment]
Ping @brexis?

**Comment by 4n70w4** [comment]
any news?

**Pull request closed without merging**
