### PR TITLE
Added symfony 4 support

### LINKED ISSUE #12: Support Symfony 4 components
Symfony has updated to 4.0 and it would be nice if this package would also support these.

### PR DESCRIPTION
**Pull request by MyDigitalLife**
Seeing that there a no major changes that seem the [conflict](https://github.com/symfony/workflow/blob/master/CHANGELOG.md) with this bundle we can just add Symfony 4 support.

Closes #12

### CODE REVIEW

**Comment by lguima** [comment]
Could this PR fix this error?

screenshot from 2018-01-23 13-39-29

**Comment by MyDigitalLife** [comment]
Yes it should. I'm hoping @brexis will be review the open pull requests soon and this will be fixed.

As a workaround I added symfony/event-dispatcher ^3.0 to my composer.json and this fixed the issue. You could try that.

**Comment by lguima** [comment]
@MyDigitalLife, did you add this dependency to `composer.json` of your project or of **laravel-workflow**?

I tried some few approaches but none worked.

**Comment by MyDigitalLife** [comment]
@lguima I added it to my project composer.json. It could be that you have another package that is giving the conflict. I'm afraid you will have to wait until @brexis updates the package.

**Comment by brexis** [comment]
Fixed in #18

**Pull request closed without merging**
