### PR TITLE
Laravel 58 support

### PR DESCRIPTION
**Pull request by personnage**

### CODE REVIEW

**Comment by dinamic** [comment]
ping @brexis

**Comment by 4n70w4** [comment]
@personnage can you publish your fork in the composer?

**Comment by masunov** [comment]
https://packagist.org/packages/symfony-rot-ebal/laravel-workflow

@dinamic @4n70w4

**Comment by dannykopping** [comment]
@brexis are you still active on this project?

**Comment by brexis** [comment]
Dear @personnage thank you for this.

**Pull request merged**
